import numpy as np

data = np.load('preprocessed_chess_data.npz')

# print(data['bitboards'][:5])
# print("--------------------------------")
# print(data['eval'][:5])
# print("--------------------------------")
print(data['piece_count'][:5])
print("--------------------------------")
print(data['piece_mobility'][:5])
print("--------------------------------")
print(data['player_turn'][:5])
print("--------------------------------")
print(data['en_passant_available'][:5])
print("--------------------------------")
print(data['in_check'][:5])
print("--------------------------------")
print(data['castling_rights'][:5])
print("--------------------------------")
print(data['pst_score'][:5])
print("--------------------------------")
print(data['check_one_move_away'][:5])
print("--------------------------------")
print(data['legal_moves_per_side'][:5])
print("--------------------------------")
print(data['issolated_pawns'][:5])
print("--------------------------------")
print(data['double_pawns'][:5])
print("--------------------------------")
print(data['rook_on_7th_rank'][:5])
print("--------------------------------")
print(data['rook_on_semi_open_file'][:5])
print("--------------------------------")
print(data['rooks_on_same_file'][:5])
print("--------------------------------")
print(data['is_forking'][:5])
print("--------------------------------")
print(data['fork_available'][:5])
print("--------------------------------")
print(data['bishop_activity'][:5])
print("--------------------------------")
print(data['pinned_pieces'][:5])
print("--------------------------------")
print(data['number_of_hanging_pieces'][:5])
print("--------------------------------")
print(data['hanging_pieces_bitboards'][:5])
print("--------------------------------")
print(data['center_controll'][:5])
print("--------------------------------")